Movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),

  
    path('create/', views.create, name='create'),

    path('<int:id>/', views.detail, name ='detail'),

    path('<int:id>/update/',views.update, name='update'),

    path('<int:id>/delete/',views.delete, name='delete'),

    # path('<int:id>/delete/', views.delete ),

    # path('<int:id>/edit/', views.edit),
    # path('<int:id>/update/', views.update),

    # path('<int:id>/detail/',views.detail),
]

movies/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)

movies/views.py
from django.shortcuts import render, redirect
from .models import movie

# Create your views here.
def index(request):
    movies = movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'index.html',context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title-en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open-date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch-grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster-url')
        description = request.POST.get('description')

        movie.objects.create(
            title = title,
            title_en = title_en,
            audience = audience,
            open_date = open_date,
            genre = genre,
            watch_grade = watch_grade,
            score = score,
            poster_url = poster_url,
            description = description,
        )
        return redirect('movies:index')
    else:
        return render(request, 'form.html')

def detail(request, id):
    Movie=movie.objects.get(id=id)
    context = {
        'movies' : Movie,
    }
    return render(request,'detail.html',context)

def update(request, id):
    Movie=movie.objects.get(id=id)
    context = {
        'movies' : Movie,
    }
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title-en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open-date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch-grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster-url')
        description = request.POST.get('description')

        Movie.title = title
        Movie.title_en = title_en
        Movie.audience = audience
        Movie.open_date = open_date
        Movie.genre = genre
        Movie.watch_grade = watch_grade
        Movie.score = score
        Movie.poster_url = poster_url
        Movie.description = description

        Movie.save()
        return redirect('movies:index')
    else:
        return render(request, 'edit.html', context)

    #  title = request.POST.get('title')
    #  title_en = request.POST.get('text_en')
    #  audience = request.POST.get('audience')
    #  open_date = request.POST.get('open_date')
    #  genre = request.POST.get('genre')
    #  watch_grade = request.POST.get('watch_grade')
    #  score = request.POST.get('score')
    #  poster_url = request.POST.get('poster_url')
    #  description = request.POST.get('description')
def delete(request, id):
    Movie=movie.objects.get(id=id)
    Movie.delete()

    return redirect('movies:index')

movies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand">MOVIE</a>
      <a href="{% url 'movies:create'  %}" class="navbar-brand">new</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </nav>
<div class="container mt-5">
    {% block body %}

    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="card" style="width: 18rem;">
  <img src="{{movies.poster_url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{movies.title}}</h5>
    <p class="card-text">{{movies.title_en}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{movies.genre}} | {{moviess.score}} | {{movies.audience}} | {{movies.open_date}}</li>
    <li class="list-group-item">{{movies.watch_grade}}</li>
    <li class="list-group-item">{{movies.description}}</li>
  </ul>
  <div class="card-body">
      <a href="{% url 'movies:index' %}" class="btn btn-outline-success">목록</a>
      <a href="{% url 'movies:update' movies.id %}"  class="btn btn-outline-success">수정</a>
      <a href="{% url 'movies:delete' movies.id %}" class="btn btn-outline-success">삭제</a>
  </div>
</div>

 

</ul>
{% endblock %}

movies/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
      <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label col-form-label-lg">영화명</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-lg" id="title" name="title" value="{{movies.title}}">
        </div>
      </div>
      <div class="form-group row">
          <label for="title-en" class="col-sm-2 col-form-label col-form-label-lg">영화명(영문)</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="title-en" name="title-en" value="{{movies.title_en}}"v>
          </div>
      </div> 
      <div class="form-group row">
          <label for="audience" class="col-sm-2 col-form-label col-form-label-lg">누적 관객수</label>
          <div class="col-sm-10">
            <input type="number" class="form-control form-control-lg" id="audience" name="audience" value="{{movies.audience}}">
          </div>
      </div>
      <div class="form-group row">
          <label for="open-date" class="col-sm-2 col-form-label col-form-label-lg">개봉일</label>
          <div class="col-sm-10">
            <input type="date" class="form-control form-control-lg" id="open-date" name="open-date" value="{{movies.open_date|date:'Y-m-d'}}">
          </div>
      </div> 
      <div class="form-group row">
          <label for="genre" class="col-sm-2 col-form-label col-form-label-lg">장르</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="genre" name="genre" value="{{movies.genre}}">
          </div>
      </div> 
      <div class="form-group row">
          <label for="watch-grade" class="col-sm-2 col-form-label col-form-label-lg">관람등급</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="watch-grade" name="watch-grade" value="{{movies.watch_grade}}">
          </div>
      </div> 
      <div class="form-group row">
          <label for="score" class="col-sm-2 col-form-label col-form-label-lg">평점</label>
          <div class="col-sm-10">
            <input type="number" class="form-control form-control-lg" id="score" name="score"  value="{{movies.score}}" step="0.01">
          </div>
      </div> 
      <div class="form-group row">
          <label for="poster-url" class="col-sm-2 col-form-label col-form-label-lg">포스터 URL</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="poster-url" name="poster-url" value="{{movies.poster_url}}">
          </div>
      </div> 


      <div class="form-group row">
          <label for="description" class="col-sm-2 col-form-label col-form-label-lg">영화 소개</label>
          <div class="col-sm-10">
            <textarea class="form-control form-control-lg" aria-label="With textarea" id="description" name="description"> {{movies.description}}</textarea>
          </div>
      </div>

      <input type="submit" class="btn btn-success" value="수정">
   
    <!-- 영화명 : <input type="text" name='title'>
    영화명(영문) : <input type="text" name='title_en'>
    누적 관객수 : <input type="text" name='audience'>
    개봉일 : <input type="text" name='open_date'>
    장르 : <input type="date" name='genre'>
    관람등급 : <input type="text" name='watch_grade'>
    평점 : <input type="text" name='score'>
    포스터 이미지 URL : <input type="text" name='poster_url'>
    영화 소개 : <input type="text" name='description'>
    <input type="submit" value="저장"> -->
  </form>
{% endblock %}

movies/templates/form.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
      <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label col-form-label-lg">영화명</label>
        <div class="col-sm-10">
          <input type="text" class="form-control form-control-lg" id="title" name="title" placeholder="텍스트를 입력하세요">
        </div>
      </div>
      <div class="form-group row">
          <label for="title-en" class="col-sm-2 col-form-label col-form-label-lg">영화명(영문)</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="title-en" name="title-en" placeholder="텍스트를 입력하세요">
          </div>
      </div> 
      <div class="form-group row">
          <label for="audience" class="col-sm-2 col-form-label col-form-label-lg">누적 관객수</label>
          <div class="col-sm-10">
            <input type="number" class="form-control form-control-lg" id="audience" name="audience" placeholder="텍스트를 입력하세요">
          </div>
      </div>
      <div class="form-group row">
          <label for="open-date" class="col-sm-2 col-form-label col-form-label-lg">개봉일</label>
          <div class="col-sm-10">
            <input type="date" class="form-control form-control-lg" id="open-date" name="open-date" placeholder="텍스트를 입력하세요">
          </div>
      </div> 
      <div class="form-group row">
          <label for="genre" class="col-sm-2 col-form-label col-form-label-lg">장르</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="genre" name="genre" placeholder="텍스트를 입력하세요">
          </div>
      </div> 
      <div class="form-group row">
          <label for="watch-grade" class="col-sm-2 col-form-label col-form-label-lg">관람등급</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="watch-grade" name="watch-grade" placeholder="텍스트를 입력하세요">
          </div>
      </div> 
      <div class="form-group row">
          <label for="score" class="col-sm-2 col-form-label col-form-label-lg">평점</label>
          <div class="col-sm-10">
            <input type="number" class="form-control form-control-lg" id="score" name="score" placeholder="텍스트를 입력하세요" step="0.01">
          </div>
      </div> 
      <div class="form-group row">
          <label for="poster-url" class="col-sm-2 col-form-label col-form-label-lg">포스터 URL</label>
          <div class="col-sm-10">
            <input type="text" class="form-control form-control-lg" id="poster-url" name="poster-url" placeholder="텍스트를 입력하세요">
          </div>
      </div> 


      <div class="form-group row">
          <label for="description" class="col-sm-2 col-form-label col-form-label-lg">영화 소개</label>
          <div class="col-sm-10">
            <textarea class="form-control form-control-lg" aria-label="With textarea" id="description" name="description" placeholder="텍스트를 입력하세요"></textarea>
          </div>
      </div>

      <input type="submit" class="btn btn-success" value="등록">
   
    <!-- 영화명 : <input type="text" name='title'>
    영화명(영문) : <input type="text" name='title_en'>
    누적 관객수 : <input type="text" name='audience'>
    개봉일 : <input type="text" name='open_date'>
    장르 : <input type="date" name='genre'>
    관람등급 : <input type="text" name='watch_grade'>
    평점 : <input type="text" name='score'>
    포스터 이미지 URL : <input type="text" name='poster_url'>
    영화 소개 : <input type="text" name='description'>
    <input type="submit" value="저장"> -->
  </form>

{% endblock %}

movies/templates/index.html
{% extends 'base.html' %}
<div class="container mt-8">
{% block body %}
  {% for movie in movies %}

    <!-- <a href="/movies/{{movies.id}}/detail/">보기</a> -->

    <ul class="list-group">
      <li class="list-group-item">
        <a href="{{movie.id}}/">
        Title:{{movie.title}} 
        </a></li>
      <li class="list-group-item">평점:{{movie.score}}</li>
      
    </ul>

    {% endfor %}


    {% endblock %}
</div>